#ifndef __SUNXI_DSP_MSGBOX_H
#define __SUNXI_DSP_MSGBOX_H

#define SUNXI_MSGBOX_DSP 0
#define SUNXI_MSGBOX_CHANNELS_MAX 4
#define SUNXI_MSGBOX_FIFO_MSG_NUM_MAX 8

#define SUNXI_MSGBOX_OFFSET(n) (0x100 * (n))
#define SUNXI_MSGBOX_READ_IRQ_ENABLE(n) (0x20 + SUNXI_MSGBOX_OFFSET(n))
#define SUNXI_MSGBOX_READ_IRQ_STATUS(n) (0x24 + SUNXI_MSGBOX_OFFSET(n))
#define SUNXI_MSGBOX_WRITE_IRQ_ENABLE(n) (0x30 + SUNXI_MSGBOX_OFFSET(n))
#define SUNXI_MSGBOX_WRITE_IRQ_STATUS(n) (0x34 + SUNXI_MSGBOX_OFFSET(n))
#define SUNXI_MSGBOX_DEBUG_REGISTER(n) (0x40 + SUNXI_MSGBOX_OFFSET(n))
#define SUNXI_MSGBOX_FIFO_STATUS(n, p) \
	(0x50 + SUNXI_MSGBOX_OFFSET(n) + 0x4 * (p))
#define SUNXI_MSGBOX_MSG_STATUS(n, p) \
	(0x60 + SUNXI_MSGBOX_OFFSET(n) + 0x4 * (p))
#define SUNXI_MSGBOX_MSG_FIFO(n, p) (0x70 + SUNXI_MSGBOX_OFFSET(n) + 0x4 * (p))
#define SUNXI_MSGBOX_WRITE_IRQ_THRESHOLD(n, p) \
	(0x80 + SUNXI_MSGBOX_OFFSET(n) + 0x4 * (p))

/* SUNXI_MSGBOX_READ_IRQ_ENABLE */
#define RD_IRQ_EN_MASK 0x1
#define RD_IRQ_EN_SHIFT(p) ((p) * 2)

/* SUNXI_MSGBOX_READ_IRQ_STATUS */
#define RD_IRQ_PEND_MASK 0x1
#define RD_IRQ_PEND_SHIFT(p) ((p) * 2)

/* SUNXI_MSGBOX_WRITE_IRQ_ENABLE */
#define WR_IRQ_EN_MASK 0x1
#define WR_IRQ_EN_SHIFT(p) ((p) * 2 + 1)

/* SUNXI_MSGBOX_WRITE_IRQ_STATUS */
#define WR_IRQ_PEND_MASK 0x1
#define WR_IRQ_PEND_SHIFT(p) ((p) * 2 + 1)

/* SUNXI_MSGBOX_MSG_STATUS */
#define MSG_NUM_MASK 0xF
#define MSG_NUM_SHIFT 0

#endif
