#ifndef CANARD_CONSTANTS_H_
#define CANARD_CONSTANTS_H_

#define CANARD_VID 0x0100
#define CANARD_PID 0x2101
#define CANARD_FW_VERSION 0x0001

#define CANARD_CMD_SET_CTRL_ENABLE 0x80
#define CANARD_CMD_GET_RADIO_STATE 0x81
#define CANARD_CMD_SET_RADIO_STATE 0x82
#define CANARD_CMD_GET_VOLUME 0x83
#define CANARD_CMD_SET_VOLUME 0x84

#define CANARD_CMD_START_CONFIG_WRITE 0x85
#define CANARD_CMD_WRITE_CONFIG 0x86
#define CANARD_CMD_FINISH_CONFIG_WRITE 0x87

#define CANARD_CMD_START_CONFIG_READ 0x88
#define CANARD_CMD_READ_CONFIG 0x89

#define CANARD_RADIO_STATE_LEN 5
#define CANARD_RADIO_STATE_PRESET_MODE_MASK 1
#define CANARD_RADIO_MODE_SHIFT 1
#define CANARD_RADIO_MODE_MASK 0xF
#define CANARD_RADIO_MODE_FM 0
#define CANARD_RADIO_MODE_AIRBAND 1

#define CANARD_RADIO_FM_MAX_FREQ 1079
#define CANARD_RADIO_FM_MIN_FREQ 879
#define CANARD_RADIO_AIRBAND_MIN_FREQ 118000
#define CANARD_RADIO_AIRBAND_MAX_FREQ 136975

#define CANARD_RADIO_FM_DECIMAL_COUNT 1
#define CANARD_RADIO_AIRBAND_DECIMAL_COUNT 3

#define CANARD_SETTINGS_LEN 512

#endif
