#include "mainwindow.h"
#include "ui_mainwindow.h"

#include "AVQtWidgets/qrotarymenuentry.h"
#include <QLabel>

#include "AVQtWidgets/qrotarymenu.h"
#include "AVQtWidgets/clock.h"
#include "AVQtWidgets/simplemediaplayer.h"
#include "AVQtWidgets/splash.h"
#include "AVQtWidgets/compass.h"
#include "AVQtWidgets/getdata.h"
#include "AVQtWidgets/radarscope.h"
#include "AVQtWidgets/flightboard.h"
#include "AVQtWidgets/oscope.h"

// TODO: Use global to track active window jumps.
int test;

MainWindow::MainWindow(QWidget* parent)
    : QMainWindow(parent)
    , ui(new Ui::MainWindow)
{
    ui->setupUi(this);
    getData* getdata = new getData(this);
    getdata->start();

    Clock* clockW = new Clock(this);
    simplemediaplayer* mediaPlayer = new simplemediaplayer(this);

    QRotaryMenuEntry* entry1 = new QRotaryMenuEntry("Clock", this, clockW);
    QRotaryMenuEntry* entry2 = new QRotaryMenuEntry("Video", this, mediaPlayer);
    QRotaryMenuEntry* entry3 = new QRotaryMenuEntry("Entry 3", this, nullptr);
    QRotaryMenuEntry* entry4 = new QRotaryMenuEntry("Entry 4", this, nullptr);
    QRotaryMenuEntry* entry5 = new QRotaryMenuEntry("Entry 5", this, nullptr);
    QRotaryMenuEntry* entry6 = new QRotaryMenuEntry("Entry 6", this, nullptr);
    QRotaryMenuEntry* entry7 = new QRotaryMenuEntry("Entry 7", this, nullptr);
    QList<QRotaryMenuEntry*> rotary_menu_entries;
    rotary_menu_entries.append(entry1);
    rotary_menu_entries.append(entry2);
    rotary_menu_entries.append(entry3);
    rotary_menu_entries.append(entry4);
    rotary_menu_entries.append(entry5);
    rotary_menu_entries.append(entry6);
    rotary_menu_entries.append(entry7);

    QRotaryMenu* rotary_menu = new QRotaryMenu(
        rotary_menu_entries,
        this
    );

    this->installEventFilter(rotary_menu);



    // labels.append(ui->labelOption1); // Example for referencing a label generated by .ui.

}

MainWindow::~MainWindow() {
    delete ui;
}

